language: node_js
node_js: 
  - "8.6.0"
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
before_script:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: elasticbeanstalk
  access_key_id: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: "$region"
  app: "$app"
  env: "$env"
  bucket_name: "$bucket_name"